name: Run Test with Agent

on:
  workflow_dispatch: 

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'zulu'
      
    - name: Download agent jars from GitHub Packages
      env:
        AGENT_VERSION: "1.3"
      run: |
        # Download main agent jar
        curl -u "${{ github.actor }}:${{ secrets.GH_PACKAGES_READ_TOKEN }}" \
          -fL "https://maven.pkg.github.com/fixate-dev/Fixate/com/example/fixate-agent/${AGENT_VERSION}/fixate-agent-${AGENT_VERSION}.jar" \
          -o fixate-agent.jar

        # Download bootstrap jar
        curl -u "${{ github.actor }}:${{ secrets.GH_PACKAGES_READ_TOKEN }}" \
          -fL "https://maven.pkg.github.com/fixate-dev/Fixate/com/example/fixate-agent/${AGENT_VERSION}/fixate-agent-${AGENT_VERSION}-bootstrap.jar" \
          -o fixate-agent-bootstrap.jar

        # Verify both jars were downloaded
        echo "Main agent jar contents:"
        jar tf fixate-agent.jar | head -20
        echo "Bootstrap jar contents:"
        jar tf fixate-agent-bootstrap.jar
      
    - name: Run tests with agent
      run: |
         mvn test -DargLine="-javaagent:/$(pwd)/fixate-agent.jar -Xmx16g"

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: javapoet/reports/
