name: Run Fixate With SARIF Output

on:
  workflow_dispatch:

permissions:
  security-events: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'zulu'

    - name: Download agent jars from GitHub Packages
      env:
        AGENT_VERSION: "${{ vars.FIXATE_AGENT_VERSION }}"
      run: |
        # Download agent
        curl -u "${{ github.repository_owner }}:${{ secrets.FIXATE_PACKAGES_ACCESS_TOKEN }}" \
          -L "https://maven.pkg.github.com/fixate-dev/Fixate/com/example/fixate-agent/${AGENT_VERSION}/fixate-agent-${AGENT_VERSION}.jar" \
          -o fixate-agent.jar

        # Download bootstrap jar
        curl -u "${{ github.repository_owner }}:${{ secrets.FIXATE_PACKAGES_ACCESS_TOKEN }}" \
          -fL "https://maven.pkg.github.com/fixate-dev/Fixate/com/example/fixate-agent/${AGENT_VERSION}/fixate-agent-${AGENT_VERSION}-bootstrap.jar" \
          -o fixate-agent-bootstrap.jar

        # Verify both jars were downloaded
        echo "Main agent jar contents:"
        jar tf fixate-agent.jar | head -20
        echo "Bootstrap jar contents:"
        jar tf fixate-agent-bootstrap.jar

    - name: Run tests with agent
      run: |
        mvn test -DargLine="-javaagent:/$(pwd)/fixate-agent.jar -Xmx16g"
        ls 
        ls ./reports/

    - name: Convert json report to sarif
      run: |
        # Take converter out of jar
        jar xf fixate-agent.jar fixate_report_to_sarif_converter.py
        
        # Generate Sarif file
        pip install typer
        python fixate_report_to_sarif_converter.py --out reports/sarif-report.sarif

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: reports/sarif-report.sarif

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: ./reports/
